export const productGroups = [ 
  {
    "id": 1,
    "name": "a bit bubbly",
    "accentColor": "#c0539f",
    "tagLine" : "Enjoy our Bit Bubbly 100% natural* drinks with no added sugar. Now Available in 275ml paper bottles in a range of Feel Good flavours:"
  },
  {
    "id": 2,
    "name": "refreshingly still",
    "accentColor": "#f49b23",
    "tagLine" : "Enjoy our Refreshingly Still 100% natural* drinks with no added sugar. Now Available in 275ml paper bottles in a range of Feel Good flavours:"
  }
]


export const events = [ 
  {
    "id": 1,
    "name": "Crusade",
    "type" : "Social",
    "title": "Crusade of the Feet",
    "tagline": "How many footprints does it take to clear out waterways and beaches? Let’s find out!",
    "details": "Gather up all your friends, family or local community, to form your team. Feel Good Drinks Co. wants to see how long our human feet chain can reach to clean up—in May 2019 the Guinness Book of Records recorded the longest human chain of 824 people.  We feel 100% sure that we can create the longest human footprint trail, with footprints in sand, dirt or just making chalk marks with your feet and removing the bad stuff that's clogging our waterways.<br><br> Our goal is to get over 1000 people and their footprints to join us to help clean up our waterways in a celebration of the Earth, and an opportunity to create awareness about the plight of the oceans.<br><br> Gather your team and join in! All team must register to enter in the crusade.*<br><br> *Terms and conditions apply.",
    "date": "22/05/2020",
    "register": "/register/feet",
    "video": "",
    "bgImage": "girlatbeach1200.png"
  },
  {
    "id": 2,
    "name": "Go Free!",
    "type" : "video",
    "title": "",
    "tagline": "The 12-week challenge to live plastic-free.",
    "details": "Post your progress regularly through our Instagram and Facebook pages to tell us about how you are getting plastic-free, and share your exciting new plastic-free innovations.To find how to go plastic free in our 12 week challenge, watch the video above.",
    "date": "22/08/2020",
    "register": "",
    "video": "https://www.youtube.com/embed/qtVxWoVssJQ",
    "bgImage": "gofreeimg_bg.png"
  }
]

export const products = [ 
  {
    "id": 1,
    "productGroup": 1,
    "name": "Orange, Passion Fruit & Water",
    "nutritionalVolume": "100ml",
    "energy": "121kJ (29kcal)",
    "fat": "0g of which saturates 0g",
    "carbs": "6.8g of which sugars* 6.5g",
    "protein": "0.1g",
    "salt": "<0.01g",
    "ingredients": "Fruit Juice from concentrate 67% (Apple, Orange, Mango, Lemon, Carrot, Passionfruit, Acerola, Peach, Apricot), Sparkling Water, Natural Flavouring, Stabiliser (pectin)",
    "color": "#000000",
    "bottleGroupImage": "bb_pink.png",
    "bottleHeroImage": "bb_pink_bigbottle_01.png",
    "fruitGroupImage": "bb_fruit_pink.png",
    "fruit1Image": "bb_fruit_pink_orange.png",
    "fruit1Description": "Our oranges are navel orange, varieties are grown in the southern growing regions of NSW Australia & Nevada California USA. Navel oranges are a rich source of Vitamin C rich in colour, sweet and juicy for the best taste sensation. ",
    "fruit2Image": "bb_fruit_pink_passion.png",
    "fruit2Description": "Our passion fruits are grown in Australian farming region of Queensland and California USA. The purple fruit is originally native to Southern Brazil through Paraguay to northern Argentina. They contain over 50% Vitamin A and C. "
  },
  {
    "id": 2,
    "productGroup": 1,
    "name": "Cranberry, Lime & Water",
    "nutritionalVolume": "100ml",
    "energy": "112kJ (27kcal)",
    "fat": "0g of which saturates 0g",
    "carbs": "6.3g of which sugars* 6.0g",
    "protein": "0.1g",
    "salt": "0.04g",
    "ingredients": "Mixed Fruit Juices from concentrate 62% (Apple, Cranberry, Lime), Sparkling Water, Vegetable and Plant Extracts, Natural Flavourings",
    "color": "#000000",
    "bottleGroupImage": "bb_red.png",
    "bottleHeroImage": "bb_red_bigbottle_01.png",
    "fruitGroupImage": "bb_fruit_red.png",
    "fruit1Image": "bb_fruit_red_cranberry.png",
    "fruit1Description": "Cranberries are most commonly grown in North America, they are heather and have rich in various healthy vitamins.",
    "fruit2Image": "bb_fruit_red_lime.png",
    "fruit2Description": "Lime are a tropical and subtropical fruit, widely grown in the Mediterranean and Southern Americas. They have high in vitamin C."
  },
  {
    "id": 3,
    "productGroup": 1,
    "name": "Apple, Elderflower & Water",
    "nutritionalVolume": "100ml",
    "energy": "110kJ (26kcal)",
    "fat": "0g of which saturates 0g",
    "carbs": "6.3g of which sugars* 6.0g",
    "protein": "0.1g",
    "salt": "<0.01g",
    "ingredients": "Fruit juice from Concentrate 61% (Apple, Acerola), Sparkling Water, Natural Flavourings",
    "color": "#000000",
    "bottleGroupImage": "bb_green.png",
    "bottleHeroImage": "bb_green_bigbottle_01.png",
    "fruitGroupImage": "bb_fruit_green.png",
    "fruit1Image": "bb_fruit_green_apple.png",
    "fruit1Description": "The Granny Smith apple was developed in Australia 1868, they are tart in flavour and are a high-antioxidant.",
    "fruit2Image": "bb_fruit_green_elder.png",
    "fruit2Description": "The white flower blossom of the elderberry tree is commonly used in British drinks and deserts. the delicate flavour of the elderflower has medicinal properties such as anti-inflammatory and rich in bioflavonoids."
  },
  {
    "id": 4,
    "productGroup": 2,
    "name": "Orange, Mango & Water",
    "nutritionalVolume": "100ml",
    "energy": "121kJ (29kcal)",
    "fat": "0g of which saturates 0g",
    "carbs": "6.8g of which sugars* 6.5g",
    "protein": "0.2g",
    "salt": "<0.01g",
    "ingredients": "Fruit Juices from concentrate 67% (Apple, Orange, Mango, Lemon, Carrot, Passionfruit, Acerola, Peach, Apricot), Water, Natural Flavouring, Stabiliser (pectin)",
    "color": "#000000",
    "bottleGroupImage": "rs_orange.png",
    "bottleHeroImage": "rs_orange_bigbottle_01.png",
    "fruitGroupImage": "rs_fruit_orange.png",
    "fruit1Image": "rs_fruit_orange_oranges.png",
    "fruit1Description": "Our oranges are navel orange, varieties are grown in the southern growing regions of NSW Australia & Nevada California USA. Navel oranges are a rich source of Vitamin C rich in colour, sweet and juicy for the best taste sensation. ",
    "fruit2Image": "rs_fruit_orange_mango.png",
    "fruit2Description": "The honey mango variety is chosen for its sweet and creamy taste and contain over 20 vitamins and minerals."
  },
  {
    "id": 5,
    "productGroup": 2,
    "name": "Lemon, Elderflower & Water",
    "nutritionalVolume": "100ml",
    "energy": "139kJ (33kcal)",
    "fat": "0g of which saturates 0g",
    "carbs": "8.0g of which sugars* 7.8g",
    "protein": "0.1g",
    "salt": "<0.01g",
    "ingredients": "Fruit Juice from Concentrate 65% (Apple, Grape, Lemon, Acerola), Water, Natural Flavourings",
    "color": "#000000",
    "bottleGroupImage": "rs_yellow.png",
    "bottleHeroImage": "rs_yellow_bigbottle_01.png",
    "fruitGroupImage": "rs_fruit_yellow.png",
    "fruit1Image": "rs_fruit_lemon.png",
    "fruit1Description": "Lemons are distinctive in flavour and rich in colour thrive in the warm climate regions of Italy, California and Florida. They contain high quantities of Vitamin C.",
    "fruit2Image": "rs_fruit_yellow_elder.png",
    "fruit2Description": "The white flower blossom of the elderberry tree is commonly used in British drinks and deserts. the delicate flavour of the elderflower has medicinal properties such as anti-inflammatory and rich in bioflavonoids."
  },
  {
    "id": 6,
    "productGroup": 2,
    "name": "Cranberry, Pomegranate & Water",
    "nutritionalVolume": "100ml",
    "energy": "128kJ (31kcal)",
    "fat": "0g of which saturates 0g",
    "carbs": "7.3g of which sugars* 7.2g",
    "protein": "0.1g",
    "salt": "<0.01g",
    "ingredients": "Fruit juice from Concentrate 61% (Apple, Acerola), Sparkling Water, Natural Flavourings",
    "color": "#000000",
    "bottleGroupImage": "rs_red.png",
    "bottleHeroImage": "rs_red_bigbottle_01.png",
    "fruitGroupImage": "rs_fruit_red.png",
    "fruit1Image": "rs_fruit_red_cranberry.png",
    "fruit1Description": "Cranberries are most commonly grown in North America, they are heather and have rich in various healthy vitamins.",
    "fruit2Image": "rs_fruit_red_pommy.png",
    "fruit2Description": "The pomegranate are jewel-like seeds are rich in vitamin C, potassium. They are grown in Middle East, South Asia, and the Mediterranean region."
  }
]