export const GET_CONTENT_BLOCKS = 'GET_CONTENT_BLOCKS'
export const SET_CONTENT_BLOCKS = 'SET_CONTENT_BLOCKS'

export const GET_PRODUCT_GROUPS = 'GET_PRODUCT_GROUPS'
export const SET_PRODUCT_GROUPS = 'SET_PRODUCT_GROUPS'