export const GET_CONTENT_BLOCKS = 'GET_CONTENT_BLOCKS'
export const SET_CONTENT_BLOCKS = 'SET_CONTENT_BLOCKS'

export const GET_PRODUCT_GROUPS = 'GET_PRODUCT_GROUPS'
export const SET_PRODUCT_GROUPS = 'SET_PRODUCT_GROUPS'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const SET_PRODUCTS = 'SET_PRODUCTS'

export const GET_EVENTS = 'GET_EVENTS'
export const SET_EVENTS = 'SET_EVENTS'