version: '3.1'
services:

  app:
    container_name: feel_good
    build: .
    restart: always
    depends_on: 
      - db
    volumes:
      - .:/var/www/html/
    networks:
      - traefik
      - internal
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:backend.endgame-feelgood.com"
      - "traefik.port=80"
      - "traefik.protocol=http"
      - "traefik.backend=feelgood"
      - "traefik.frontend=feelgood"
    ports:
      - "8090:80"

  db:
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - internal
    labels:
      - "traefik.enable=false"

  adminer:
    image: adminer
    restart: always
    ports:
      # Deployment
      - 8080:8080


networks:
  internal:
  traefik:
    external: true